import ContactSection from "@/components/ContactSection";
import { AqIcon } from "@/components/AqIcons";

const values = [
  ["Claridad antes que promesa", "Primero entendemos la operación. Después proponemos una ruta técnica defendible.", "target"],
  ["Sistema alrededor del negocio", "No obligamos a tu empresa a operar como una plantilla genérica. Adaptamos el sistema a los procesos que sí hacen sentido.", "strategy"],
  ["Proyectos selectivos", "Tomamos retos donde hay complejidad real, decisión de dirección y oportunidad clara de construir valor.", "shield"],
  ["Monterrey + operación nacional", "Tenemos presencia física en Monterrey y capacidad de acompañamiento para proyectos en todo México.", "globe"],
  ["Soporte recurrente", "La relación no termina al arrancar. Acompañamos la evolución del sistema y de la operación.", "database"],
  ["Integridad técnica", "Si no somos la mejor opción, lo decimos. Si el proyecto requiere más de lo previsto, también.", "check"],
];

export default function Nosotros() {
  return <><section className="aq-service-hero"><div className="aq-wrap"><div className="aq-service-grid"><div><div className="aq-eyebrow">Nosotros · Monterrey · operación nacional</div><h1 className="aq-service-title"><span>Construimos</span> sistemas alrededor de tu operación</h1><p className="aq-service-sub">Alphaqueb trabaja con empresas que ya tienen operación real, procesos propios y sistemas que empezaron a quedarse cortos. Nuestra función no es venderte una plantilla: es entender dónde está el límite, diseñar una ruta y construir lo que tu negocio necesita para seguir creciendo.</p></div><div className="aq-panel"><span className="aq-panel-tag">Posicionamiento</span><div className="aq-panel-head"><div><div className="title">Empresas con operación compleja</div><div style={{ fontFamily: "var(--aq-font-head)", fontSize: 36, lineHeight: 1, marginTop: 6 }}>DIAGNÓSTICO + IMPLEMENTACIÓN + SOPORTE</div></div><div className="aq-live"><span className="aq-live-dot" />ACTIVO</div></div><p className="aq-section-lead">Trabajamos con dirección, responsables de operación y equipos de tecnología que ya saben que instalar software no resuelve por sí solo una operación desordenada.</p></div></div></div></section><section className="aq-section compact"><div className="aq-wrap"><div className="aq-section-head"><span className="aq-section-tag">Valores</span><div><h2 className="aq-section-title">Cómo construimos <span className="accent">confianza</span>.</h2><p className="aq-section-lead">Principios operativos para cada diagnóstico, cada decisión técnica y cada entregable.</p></div></div><div className="aq-grid-3">{values.map(([title, description, icon], index) => <article key={title} className="aq-card"><div className="aq-card-num">V/{String(index+1).padStart(2,"0")}</div><div className="aq-card-icon"><AqIcon name={icon} size={32}/></div><h3 className="aq-card-title">{title}</h3><p className="aq-card-desc">{description}</p></article>)}</div></div></section><ContactSection /></>;
}
